version: "3"
services:
  web:
    image: "pebreo/cnug:1.5"
    # build: .
    ports:
      - "80:80"
    depends_on:
      - db
  db:
    image: "mcr.microsoft.com/mssql/server:2017-latest-ubuntu"
    environment:
      SA_PASSWORD: "Your_password123"
      ACCEPT_EULA: "Y"
