version: "3"
services:
  web:
    image: "pebreo/cnug:1.1"
    # build: .
    ports:
      - "80:80"
  # db:
  #   image: "mcr.microsoft.com/mssql/server:2017-latest-ubuntu"
  #   environment:
  #     SA_PASSWORD: "Your_password123"
  #     ACCEPT_EULA: "Y