version: "3.4"
services:
  web:
    image: "pebreo/cnug:1.9"
    # build: .
    restart: always
    ports:
      - "8888:80"
    depends_on:
      - db
    networks: 
      - todonetwork
  db:
    image: "mcr.microsoft.com/mssql/server:2017-CU8-ubuntu"
    environment:
      SA_PASSWORD: "Your_password123"
      ACCEPT_EULA: "Y"
    ports:
      - 1433:1433
    networks:
      - todonetwork

networks:
  todonetwork:
    driver: bridge
    
    